TodoApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('todolist/', include('todolist.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/todolist/', permanent=True)),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todolist/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addtodo', views.addnewtodo, name='addtodo'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('delete_all/', views.delete_all, name='delete_all'),
    path('update/<int:pk>/', views.update_status, name='update_status'),
    path('sentmail/', views.sentmail, name='sentmail'),
]

todolist/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

PRIORITY_CHOICES = (
    ('High', 'High'),
    ('Medium', 'Medium'),
    ('Low', 'Low'),
)

POSSIBLE_STATUSES = (
    ('Completed', 'Completed'),
    ('Incomplete', 'Incomplete')
)


class TodoListItem(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    todoTitle = models.CharField(max_length=50)
    todoDescription = models.CharField(max_length=400)
    todoDateTime = models.DateTimeField(auto_now_add=True)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='High')
    status = models.CharField(max_length=10, choices=POSSIBLE_STATUSES, default='Incomplete')

    # # Metadata
    # class Meta:
    #     ordering = ['-todoDateTime']

    # Methods
    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('model-detail-view', args=[str(self.id)])

    def __str__(self):
        return self.todoTitle

todolist/forms.py
from django import forms
from .models import PRIORITY_CHOICES, POSSIBLE_STATUSES


class AddNewTodo(forms.Form):
    title = forms.CharField(max_length=100)
    description = forms.CharField(max_length=1000)
    # datetime = forms.DateTimeField(help_text="Enter Date")
    priority = forms.ChoiceField(choices=PRIORITY_CHOICES)
    status = forms.ChoiceField(choices=POSSIBLE_STATUSES)


class SentEmail(forms.Form):
    mailid = forms.EmailField()

todolist/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404,redirect
from .models import TodoListItem
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic
from .forms import AddNewTodo, SentEmail
# from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
# Create your views here.


@login_required()
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    todolist = TodoListItem.objects.filter(creator=request.user)

    print(todolist)

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', {'todoList': todolist})


def addnewtodo(request):
    # todo = get_object_or_404(AddNewTodo)
    if request.method == 'POST':
        form = AddNewTodo(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            # datetime = form.cleaned_data['datetime']
            priority = form.cleaned_data['priority']
            status = form.cleaned_data['status']

            todo = TodoListItem.objects.create(
                creator=request.user,
                todoTitle=title,
                todoDescription=description,
                todoDateTime=datetime.now(),
                priority=priority,
                status=status,
            )
            todo.save()

            return HttpResponseRedirect(reverse('index'))
    else:
        form = AddNewTodo()
        return render(request, 'add_new_todo.html', {'form': form})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

#
# def change_status(request):
#     TodoListItem.objects.filter()


def delete(request, pk):
    todo_item = get_object_or_404(TodoListItem, pk=pk)
    todo_item.delete()
    return HttpResponseRedirect(reverse('index'))


def delete_all(request):
    todo_item = TodoListItem.objects.filter(creator=request.user)
    todo_item.delete()
    return HttpResponseRedirect(reverse('index'))


def update_status(request, pk):
    todo_item = get_object_or_404(TodoListItem, pk=pk)
    if todo_item.status == 'Complete':
        todo_item.status = 'Incomplete'
        todo_item.save()
    else:
        todo_item.status = 'Complete'
        todo_item.save()
    return HttpResponseRedirect(reverse('index'))


def sentmail(request):
    if request.method == 'POST':
        form = SentEmail(request.POST)
        mailid = []
        if form.is_valid():
            mailid.append(form.cleaned_data['mailid'])
            print(type(mailid))
            send_mail(
                TodoListItem.todoTitle,
                TodoListItem.todoDescription,
                'vedansh.kedia.iitb@gmail.com',
                mailid,
                fail_silently=False)
            return HttpResponseRedirect(reverse('index'))
    else:
        form = SentEmail()
        return render(request, 'sentmail.html', {'form': form})

todolist/templates/add_new_todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add New Todo</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}
{#    <form action="{% url 'addtodo' %}" method="POST">#}
{#    {% csrf_token %}#}
{#    <table>#}
{#        {{ form.as_p }}#}
{#    </table>#}
{#    <input type="submit" value="Submit">#}
{#    </form>#}
{#{% endblock %}#}


{#-----------------------new add todoform------------------#}

<div class="row justify-content-md-center align-items-center login">
<div class="col-sm-8">
<div class="card text-center align-self-center  h-100">
      <div class="card-header">
        Add New Todo
      </div>
      <div class="card-body">
            <div class="row">
                <form action="{% url 'addtodo' %}" method="POST" class="container">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="id_title" class="col-sm-3 col-form-label">Title:</label>
                        <input type="text" name="title" maxlength="100" required="" id="id_title" class="col-sm-8">
                    </div>
                    <div class="form-group row">
                        <label for="id_description" class="col-sm-3 col-form-label">Description:</label>
                        <input type="text" name="description" maxlength="1000" required="" id="id_description" class="col-sm-8">
                    </div>
                    <div class="form-group row">
                        <label for="id_status" class="col-sm-3 col-form-label">Status:</label>
                        <select name="status" id="id_status" class="col-sm-8">
                            <option value="Incomplete">Incomplete</option>
                            <option value="Completed">Complete</option>
                        </select>
                    </div>
                    <div class="form-group row">
                        <label for="id_priority"class="col-sm-3 col-form-label">Priority:</label>
                        <select name="priority" id="id_priority" class="col-sm-8">
                            <option value="High">High</option>
                            <option value="Medium">Medium</option>
                            <option value="Low">Low</option>
                        </select>
                    </div>

                    <input type="submit" value="Submit" class="btn btn-primary btn-block">
{#                        <input type="submit" class="btn btn-primary btn-block" value="login" />#}
{#                        <input type="hidden" name="next" value="{{ next }}" />#}
                </form>
            </div>
        </div>
{#    <div class="card-footer">#}
{#        <a href="{% url 'password_reset' %}">Lost password?</a>#}
{#        <a href="{% url 'signup' %}">New?</a>#}
{#    </div>#}
</div>
</div>
</div>

{% endblock %}


{#-----------------------New todoform copy------------------#}


{#----------------#}
{#<label for="id_title">Title:</label>#}
{#<input type="text" name="title" maxlength="100" required="" id="id_title">#}
{#<label for="id_description">Description:</label>#}
{#<input type="text" name="description" maxlength="1000" required="" id="id_description">#}
{#<label for="id_priority">Priority:</label>#}
{#<select name="priority" id="id_priority">#}
{#  <option value="High">High</option>#}
{##}
{#  <option value="Medium">Medium</option>#}
{##}
{#  <option value="Low">Low</option>#}
{##}
{#</select>#}
{#<label for="id_status">Status:</label>#}
{#<select name="status" id="id_status">#}
{#  <option value="Completed">Completed</option>#}
{##}
{#  <option value="Incomplete">Incomplete</option>#}
{##}
{#</select>#}



</body>
</html>

todolist/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Todo App</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/font/octicons.min.css">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">

    {% if user.is_authenticated %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light  d-flex justify-content-center">
      <a class="navbar-brand" href="{% url 'index' %}">TodoApp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'addtodo' %}">Add Todo</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'delete_all' %}">Delete all</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>

        </ul>
      </div>
    </nav>
  {% endif %}
          {% block content %}{% endblock %}

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    </div>

</body>
</html>

todolist/templates/index.html
{% extends "base.html" %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



    {% block content %}
        <div class="table-responsive-xl">
        <table class="table">
            <thead class="thead-dark">
                <tr class="row">

                    <th class="col-lg-3">Title</th>
                    <th class="col-lg-7">Todo Description</th>
                    <th class="col-lg-2">Options</th>
                </tr>
            </thead>

            {% for todo in todoList %}
                <tr id="{{ todo.id }}" class="{{ todo.priority }} {{ todo.status }} row">
                    <td class="col-lg-3 title">
                        {% if todo.status == 'Complete' %}<del>{% endif %}{{ todo.todoTitle }}{% if todo.status == 'Complete' %}</del>{% endif %}</td>
                    <td class="col-lg-7 desc">{{ todo.todoDescription }}</td>
                    <td class="col-lg-2 opt">
                        <div class="btn-group dropdown-menu-left">
{#                          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
                              <span class="octicon octicon-grabber display-block" id="dropdownMenuButton"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
{#                          </button>#}
                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="{% url 'delete' todo.pk %}"><span class="octicon octicon-trashcan" aria-hidden="true"></span></a>
                              <a class="dropdown-item" href="{% url 'sentmail' %}"><span class="octicon octicon-mail" aria-hidden="true"></span></a>
                              <a class="dropdown-item" href="{% url 'update_status' todo.pk %}">
                                  {% if todo.status == 'Complete' %}
                                      <span class="octicon octicon-tasklist" aria-hidden="true"></span>
                                      {% else %} <span class="octicon octicon-three-bars" aria-hidden="true"></span>
                                  {% endif %}
{#                                  Status: {{ todo.status }}</a>#}
{#                              <div class="dropdown-divider"></div>#}
{#                              <a class="dropdown-item disabled" href="{% url 'update_status' todo.pk %}">{{ todo.todoDateTime }}</a>#}
                          </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        </table>
        </div>
    {% endblock %}
</body>
</html>

todolist/templates/sentmail.html
{% extends 'base.html' %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Send Email</title>
</head>
<body>
{% block content %}
{#<form method="post">#}
{#    {% csrf_token %}#}
{#    <label for="id_mailid">Mailid:</label>#}
{#    <input type="email" name="mailid" required="" id="id_mailid">#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="Submit">#}
{#</form>#}



<div class="row justify-content-md-center align-items-center login">
<div class="col-sm-8">
<div class="card text-center align-self-center  h-100">
      <div class="card-header">
        Enter your registered E-Mail ID
      </div>
      <div class="card-body">
            <div class="row">
                <form method="post" action="" class="container">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="id_mailid" class="col-sm-3 col-form-label">Email:</label>
                        <input type="email" name="mailid" maxlength="254" required="" id="id_mailid" class="col-sm-8">
                    </div>
                  <input type="submit" class="btn btn-primary btn-block" value="Submit">
                </form>
            </div>
        </div>
</div>
</div>
</div>

{% endblock %}

</body>
</html>

todolist/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
{#  <h1>Create account - The Great Django Blog</h1>#}
{##}
{#         <form method="post" >#}
{#             {% csrf_token %}#}
{#             <table>#}
{#                {{ form.as_table }}#}
{#                 <tr>#}
{#                    <td></td>#}
{#                    <td><input type="submit" name="submit" value="signup" /></td>#}
{#                </tr>#}
{#             </table>#}
{#         </form>#}




{#-----------login form----------------------#}

<div class="row justify-content-md-center align-items-center login">
<div class="col-sm-8">
<div class="card text-center align-self-center  h-100">
      <div class="card-header">
        Create New Account!
      </div>
      <div class="card-body">
            <div class="row">

                <form method="post" class="container">
                    {% csrf_token %}

                    <div class="form-group row">
                        <label for="id_username" class="col-sm-3 col-form-label">Username:</label>
                        <div class="col-sm-8">
                        <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" class="col-sm-12">
                            <br><small id="usernameHelp" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="id_password1" class="col-sm-3 col-form-label">Password:</label>
                        <div class="col-sm-8">
                        <input type="password" name="password1" required="" id="id_password1" class="col-sm-12">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="id_password2" class="col-sm-3 col-form-label">Re-Enter Password:</label>
                        <div class="col-sm-8">
                        <input type="password" name="password2" required="" id="id_password2" class="col-sm-12"><br>
                        <small class="helptext form-text text-muted">
                            <ul>
                                <li>
                                    Your password can't be too similar to your other personal information.
                                </li>
                                <li>Your password must contain at least 8 characters.</li>
                                <li>Your password can't be a commonly used password.</li>
                                <li>Your password can't be entirely numeric.</li>
                            </ul>
                        </small>
                            </div>
                    </div>
                    <input type="submit" name="submit" value="signup" class="btn btn-primary btn-block">
{#                    <input type="submit" class="btn btn-primary btn-block" value="login" />#}
{#                    <input type="hidden" name="next" value="{{ next }}" />#}
                </form>
            </div>
        </div>
{#    <div class="card-footer">#}
{#        <a href="{% url 'password_reset' %}">Lost password?</a>#}
{#        <a href="{% url 'signup' %}">New?</a>#}
{#    </div>#}
</div>
</div>
</div>

{% endblock %}
{#-----------------------------------------#}

</body>
</html>